name: search_algorithms
description:  A library for various search algorithms in Dart.
version: 1.0.0
repository: https://github.com/Isfandiyor-Dev/search_package.git

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
